# Generated by Django 5.0.1 on 2024-01-24 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenerateData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('loc', models.TextField(blank=True, db_column='LOC', null=True)),
                ('tm', models.BigIntegerField(blank=True, db_column='TM', null=True)),
                ('value', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'generate_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MeanWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('loc', models.TextField(blank=True, db_column='LOC', null=True)),
                ('tm', models.BigIntegerField(blank=True, db_column='TM', null=True)),
                ('wd', models.IntegerField(blank=True, db_column='WD', null=True)),
                ('ws', models.FloatField(blank=True, db_column='WS', null=True)),
                ('pa', models.FloatField(blank=True, db_column='PA', null=True)),
                ('ps', models.FloatField(blank=True, db_column='PS', null=True)),
                ('ta', models.FloatField(blank=True, db_column='TA', null=True)),
                ('td', models.FloatField(blank=True, db_column='TD', null=True)),
                ('hm', models.FloatField(blank=True, db_column='HM', null=True)),
                ('pv', models.FloatField(blank=True, db_column='PV', null=True)),
                ('rn_day', models.FloatField(blank=True, db_column='RN_DAY', null=True)),
                ('sd_tot', models.FloatField(blank=True, db_column='SD_TOT', null=True)),
                ('ca_tot', models.FloatField(blank=True, db_column='CA_TOT', null=True)),
                ('ca_mid', models.FloatField(blank=True, db_column='CA_MID', null=True)),
                ('vs', models.IntegerField(blank=True, db_column='VS', null=True)),
                ('ss', models.FloatField(blank=True, db_column='SS', null=True)),
                ('si', models.FloatField(blank=True, db_column='SI', null=True)),
                ('ts', models.FloatField(blank=True, db_column='TS', null=True)),
            ],
            options={
                'db_table': 'mean_weather',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('loc', models.TextField(blank=True, db_column='LOC', null=True)),
                ('tm', models.BigIntegerField(blank=True, db_column='TM', null=True)),
                ('stn', models.BigIntegerField(blank=True, db_column='STN', null=True)),
                ('wd', models.BigIntegerField(blank=True, db_column='WD', null=True)),
                ('ws', models.FloatField(blank=True, db_column='WS', null=True)),
                ('pa', models.FloatField(blank=True, db_column='PA', null=True)),
                ('ps', models.FloatField(blank=True, db_column='PS', null=True)),
                ('ta', models.FloatField(blank=True, db_column='TA', null=True)),
                ('td', models.FloatField(blank=True, db_column='TD', null=True)),
                ('hm', models.FloatField(blank=True, db_column='HM', null=True)),
                ('pv', models.FloatField(blank=True, db_column='PV', null=True)),
                ('rn_day', models.FloatField(blank=True, db_column='RN_DAY', null=True)),
                ('sd_tot', models.FloatField(blank=True, db_column='SD_TOT', null=True)),
                ('ca_tot', models.BigIntegerField(blank=True, db_column='CA_TOT', null=True)),
                ('ca_mid', models.BigIntegerField(blank=True, db_column='CA_MID', null=True)),
                ('vs', models.BigIntegerField(blank=True, db_column='VS', null=True)),
                ('ss', models.FloatField(blank=True, db_column='SS', null=True)),
                ('si', models.FloatField(blank=True, db_column='SI', null=True)),
                ('ts', models.FloatField(blank=True, db_column='TS', null=True)),
            ],
            options={
                'db_table': 'weather_data',
                'managed': False,
            },
        ),
    ]
